sudo: false

language: python

install:
  # https://github.com/wummel/linkchecker/issues/649
  - pip install requests==2.9.1
  - pip install LinkChecker==9.3
  - pip install pelican ghp-import markdown

  - git clone -b build https://github.com/maggick/maggner-pelican
  - git clone https://github.com/getpelican/pelican-plugins

script:
  - linkchecker --check-extern .
  - pelican

after_success:
  - ghp-import output
  #- @git push -fq https://${GH_TOKEN}@github.com/$(TRAVIS_REPO_SLUG).git gh-pages:master > /dev/null
