sudo: false

language: python

install:
  # https://github.com/wummel/linkchecker/issues/649
  - pip install requests==2.9.1
  - pip install LinkChecker==9.3
  - pip install pelican ghp-import markdown

  - git clone -b build https://github.com/maggick/maggner-pelican
  - git clone https://github.com/getpelican/pelican-plugins
  - git clone https://github.com/maggick/maggick.github.io output

script:
  - linkchecker --check-extern ./content
  - pelican

after_success:
  - ghp-import output
  - git push https://${GH_TOKEN}@github.com/maggick/maggick.github.io.git gh-pages:master
